### ISSUE TITLE
Paradox-touched Olthoi Queen climbs on top of mushroom and on Olthoi Cistern Lever area.

### ISSUE THREAD

**Issue by VokardIX** [ACEmulator/ACE-World-16PY-Patches#680]
I recall she wasn't able to do that before.  Here she can.  And can also hit a Melee D that is 766 (with a rare).  That's pretty strong.  Maybe a little TOO strong.

Thanks for all y'all do for bringing back the game. 

Kind regards,

Michael Voelkering.

**Comment by gmriggs** [comment]
Fixed by @bobigor377 in https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/681

**Comment by VokardIX** [comment]
Yea, not so much.  She still climbs up.  She's not supposed to.  Still an
issue.

**Comment by VokardIX** [comment]
both on the mushroom and over by the cistern, just like I stated in my
original statement

**Comment by VokardIX** [comment]
Verified this is still an issue after this latest update.  Queen still able to climb up on both areas.  Not a lot of fun.  
Again, thanks for all you guys do.

**Comment by gmriggs** [comment]
Can you post the exact /loc of the 2 areas you are standing?

I tested this on the mushroom behind where she spawns, near the portal. Before the update, when her scale was incorrectly set to 1.2 instead of 1.0 and didn't match the retail pcaps, she was easily able to get up all sides of that mushroom

After the update, she is only able to get up the mushroom on the side closest to the portal

There is no "special" code that the emu is running for monster movement... it is the same code that is embedded into acclient. And as per retail as the same code that is running in acclient, it was possible for her to get up on the mushroom on the side closest to the protal.

**Comment by VokardIX** [comment]
In the original game, she was never able to climb up onto the mushroom, or
where the cistern is located.  I used to tank her solo from those locations
and she was never on them.
She could reach, and occasionally hit you if you were positioned just so
when she reached, but could never climb on top of the mushroom or cistern
platform, which is just the opposite side of the portal.
Occasionally she would be able to reach you while you were on the mushroom,
but never by climbing on top of it.  No one will ever get olthoi weapons as
it is now.  You can't stop her.
I even have used Melee D rares getting over 766 Melee D, and while she
missed a lot, she still was able to one shot me 4 times.  (Yes, I had 4
different Melee D rares and used them all, and died each time.)
The original game never allowed her to leave the floor.  Unsure if you can
make that happen or not.

Perhaps scale her down to .8?  Right now she will never be defeated by
regular toons.

Regards,

MV

**Comment by gmriggs** [comment]
I asked for the 2 /locs where you were standing, which were not provided.

In the location I described, yes, she can climb up on the right side on the mushroom, the same way it was in retail.

"In the original game, she was never able to climb up onto the mushroom"

You keep saying this like ac emu "invented" special code here, that is different from retail. Which is why I just explained *this is the same code that is in acclient*. It is provable that in acclient, with no interaction from the server whatsoever, that yes, she is able to climb up on the mushroom on the side by the portal. Not someone's memory of what they "think" or remember happening from retail. Something that is provable, in the actual, unaltered game.

"Perhaps scale her down to .8?"

Her scale was 1.0, as per provable from retail information

"Right now she will never be defeated by regular toons."

Plenty of players have been able to defeat the Paradox Olthoi Queen already

**Comment by VokardIX** [comment]
I have told you where I've been standing.  In the center of the mushroom,
and the queen climbs on the mushroom, from the middle and from the left
(away from the portal)

I've been standing on the platform where the cistern is.  Again, she climbs
on it.  This was never how it was in retail.

So, either the admin of the server hasn't applied those patches, or
something else is not right.

Is there a way I can tell, as a player, if those patches have been applied
to the server?

Regards,

MV

**Comment by gmriggs** [comment]
Can you get the exact /loc of the positions where you are standing? I'm not sure exactly what the "cistern" is, would need an exact /loc

There is a /version command, which shows the current version of the code and database running on the server, although this command is only available to admins

**Comment by VokardIX** [comment]
Since every toon I have, dies almost instantly due to the queen mounting
the mushroom and the platform where the Olthoi Cistern Lever is located,
doing a /loc will be very difficult.
I'll see if I can get the admin to come along and smite all so I can get
you that info.

The Olthoi Cistern Lever is what you need to activate to allow anyone who
dies, access to the portal back to the queen's lair.
It's in the East corner, along the same wall as the large mushroom you
usually stand on to fight the queen.  You can also stand on the platform
where the Olthoi Cistern Lever is and fight as well.

http://acpedia.org/wiki/Aerbax%27s_Prodigal_Olthoi
See *In Case of Death*

   1. If anyone should die while fighting the queen, you can quickly get
   back by heading to the burrow east of Olthoi North
   <http://acpedia.org/wiki/Olthoi_North> at 44.5N 57.3E.
   2. Someone inside the Queen's Lair must use open the door to the burrow
   by using the *Olthoi Cistern
   <http://acpedia.org/wiki/Olthoi_Cistern> Lever,* located in the corner
   of the Queen's Lair.
   3. Once the door opens, use the portal just inside to be portaled back
   to the Queens Lair.
      - *Note:* Access via this entrance is restricted to players who have
      entered the Queen's Lair within the past 2 hours.

**Comment by gmriggs** [comment]
I will see if I can find some of these exact locations you have mentioned. A /loc or even a screenshot of you in the exact position would really help

Once it is ensured the exact locations are being tested, the movement can be tested purely on the client, with no interaction from the server whatsoever:

a) the exact parameters of the Paradox-touched Olthoi Queen are all 100% known from retail pcaps, and are now synced up after the update
b) the movement code for the queen can be tested purely in the client, with no server interaction whatsoever, to confirm what she does in any particular location, and the bounds of ledges she is able to climb up on as per acclient

**Comment by VokardIX** [comment]
I was able to get this from the admin.

Server database version Base: v0.7.18 Patch: v0.9.204 - compiled Tue Nov 3
06:33:03 2020


Don't know if that helps.

**Comment by gmriggs** [comment]
Yep, that would confirm that server is running the latest version of the database, which includes the queen @ scale 1.0

**Comment by VokardIX** [comment]
So, tonight, she looks a LOT smaller.

I'm wondering if my server admin had not actually patched things like he
was supposed to.
I'll see if I can get where I need to be and how it goes and let you know.

Regards,

mv

**Comment by VokardIX** [comment]
And now she's not climbing the mushroom.

It's fixed.  I really think my admin did  not apply the patch.

Thanks for working this through with me.  I have screenshots now, but don't
really think I need them.  Also the location you were wanting.

**Comment by VokardIX** [comment]
[image: image.png]

But now it's working as I real from the retail game.  Again, thanks for
sticking with me on this.

Regards,

MV

**Comment by gmriggs** [comment]
hm, that's odd if the update is just now appearing, if it was supposedly updated ~9 days ago... which server is this on?

it looks like some images were posted, but i'm just seeing them show up as "image.png", instead of the actual image

if it appears to be functioning as per retail now, glad to hear that.

**Comment by VokardIX** [comment]
Just showing the location: 0xC7B70109 [-76.892151 97.304108 92.874123]
0.408271 0.000000 0.000000 0.912861

Server is WuckFB ACE White address wuck.ddns.net:9080

Regards,

MV

**Comment by gmriggs** [comment]
cool, ty

i will make note of that testing for further testing, and to see if its different from the mushroom i tested on previously

**Comment by VokardIX** [comment]
I was all set to send you all my armor stats and screen shots and
everything.
I really appreciate your time working with me to help figure this out.

I really think when I asked the admin for the version, and what it was for,
he realized he had not applied the update and fixed it.  Just my suspicion.

Take care sir.  And I appreciate all you and the team of devs are doing.
It's greatly appreciated.

Regards,

mv
